version: '3.8'

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app:delegated #Because application is using cli, I prefer to install it somewhere else rather than /var/www/html
